homebrew_taps:
  - hashicorp/tap

homebrew_installed_packages:
  - awscli
  - dnsmasq
  - fish
  - ffmpeg
  - htop
  - jq
  - nmap
  - nomad
  - patchutils
  - python
  - restic
  - terraform
  - wget

homebrew_cask_apps:
  - audacity
  - authy
  - blender
  - blueutil
  - docker
  - firefox
  - google-chrome
  - homebrew/cask-versions/sonos-s1-controller
  # - hashicorp/tap/packer
  - iterm2
  - izotope-product-portal
  - keybase
  - licecap
  - nomad
  - postman
  - sublime-text
  - reaper
  - signal
  - switchaudio-osx
  - sysex-librarian
  - tidal
  - visual-studio-code
  - wireshark
  - zoom
  # Audio Plugins
  - fabfilter-pro-c
  - fabfilter-pro-ds
  - fabfilter-pro-g
  - fabfilter-pro-l
  - fabfilter-pro-mb
  - fabfilter-pro-q
  - fabfilter-pro-r
  - fabfilter-saturn
  - fabfilter-timeless
  - fabfilter-volcano
  - tdr-vos-slickeq
  - x32-edit

mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 1233861775, name: "Acorn 6"}
  - { id: 918858936, name: "Airmail 5"}
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 975937182, name: "Fantastical"}
  - { id: 506189836, name: "Harvest"}
  - { id: 1451685025, name: "Wireguard"}





# mas_uninstalled_apps:
#   - { id: 408981434, name: "iMovie" }
#   - { id: 409183694, name: "Keynote" }
#   - { id: 409201541, name: "Pages" }
#   - { id: 409203825, name: "Numbers" }
